config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
get 'contacts/create'
  
resources :poems, only: [:index, :show] 

resources :blogs, only: [:index, :new, :create, :edit, :update ,:destroy] do
    collection do
      post :confirm
    end
  end

resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end
  
  root 'top#index'

  

end

app/models/poem.rb
class Poem < ActiveResource::Base
    self.site = "https://murmuring-woodland-70764.herokuapp.com/"
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  before_action :set_poem, only: [:show]    

  def index
    @poems = Poem.all
  end
  
 def show
 end
 
   private
    # Use callbacks to share common setup or constraints between actions.
    def set_poem
      @poem = Poem.find(params[:id])
    end
end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/views/poems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Poems</h1>

<table>
  <thead>
    <tr>
      <th>  Title  | </th>
      <th> Content | </th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @poems.each do |poem| %>
      <tr>
        <td> <%= poem.title %>  | </td>
        <td> <%= poem.content %> | </td>
        <td><%= link_to 'Show',poem_path(poem) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/poems/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Poem Shousai</h1>

<p>
  <strong>Title:</strong> 
  <%= @poem.title %>
</p>
<p>
  <strong>Content:</strong>
  <%= @poem.content %>
</p>

<%= link_to 'Back', poems_path %>