config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
get 'contacts/create'
  
resources :poems, only: [:index, :show] 

resources :blogs, only: [:index, :new, :create, :edit, :update ,:destroy] do
    collection do
      post :confirm
    end
  end

resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end
  
  root 'top#index'

  

end

app/models/blog.rb
class Blog < ActiveRecord::Base
validates :title, presence: true
belongs_to :user

mount_uploader :pic, GzouUploader
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_blog, only: [:edit, :update, :destroy]
  def index
    @blogs=Blog.all
#    binding.pry
#    raise
  end

  def new
    if params[:back]
      @blog = Blog.new(blogs_params)
    else
      @blog = Blog.new
    end
  end
  
  def edit
    # edit, update, destroyで共通コード
  end
  
  def update
    # edit, update, destroyで共通コード
    
    if @blog.update(blogs_params)
      redirect_to blogs_path, notice: "Instagramを更新しました！"
    else
      render 'edit'
    end
  end
  
  def destroy
    # edit, update, destroyで共通コード
    @blog.destroy
    redirect_to blogs_path, notice: "Instagramを削除しました！"
  end
  
  def confirm
    @blog = Blog.new(blogs_params)
    render :new if @blog.invalid?
  end

  def create
    @blog = Blog.new(blogs_params)
    @blog.user_id = current_user.id
    if @blog.save
     # 一覧画面へ遷移して"ブログを作成しました！"とメッセージを表示します。
      redirect_to blogs_path, notice: "Instagramを新規作成しました！"
    else
      # エラー発生時に入力フォームを再描画します。
      render 'new'
    end
  end

  private
    def blogs_params
      params.require(:blog).permit(:title, :content, :user_id, :pic, :pic_cache)
    end
    
    # idをキーとして値を取得するメソッド
    def set_blog
      @blog = Blog.find(params[:id])
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/views/blogs/_form.html.erb
<%= form_for(@blog, url: choose_new_or_edit) do |f| %>
<% if @blog.errors.any? %>
  <div id="error_explanation">
    <h2><%= @blog.errors.count %>件のエラーがあります。</h2>

    <ul>
    <% @blog.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
    <%= f.label :画像 %><br>
    <%= f.file_field :pic %>
    <%= f.hidden_field :pic_cache %>
</div>
<%= f.label :タイトル %>
<%= f.text_field :title, class: 'form-control' %>
<br>
<%= f.label :内容 %>
<%= f.text_field :content, class: 'form-control' %>
<br>
<%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/blogs/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h3>以下の内容で、送信する。</h3>
    <%= form_for(@blog) do |f| %>
      <%= f.hidden_field :pic_cache %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :content %>
      <p>画像</p>
      <p></p><%= image_tag(@blog.pic.url) %></p>
      <p>タイトル:<%= @blog.title %></p>
      <p>本文:<%= @blog.content %></p>
      <%= f.submit "登録",class: 'btn btn-primary btn-block' %>
    <% end %>
    <%= form_for(@blog, url: new_blog_path, method: 'get') do |f| %>
      <%= f.hidden_field :pic %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :content %>
      <%= f.submit "もどる", name: 'back', class: 'btn btn-default btn-sm btn-success' %>
    <% end %>
  </div>
</div>

app/views/blogs/edit.html.erb
<div class="container">
<div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
<h2>Instagramを作成する</h2>
<%= render 'form' %>
</div>
</div>

app/views/blogs/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p><%= notice %></p>
    <h1>Instagram一覧</h1>
      <%= link_to "Instagramを作成", new_blog_path, class: 'btn btn-default' %>
    <% @blogs.each do |blog| %>
    <div class="row">
      

      <%= blog.user.name %>  が投稿しました。</p>
              <%= image_tag(blog.pic) %>
      <h4><strong><%= blog.title %></strong></h4>
      <p><%= blog.content %></p>

      <%= link_to "編集", edit_blog_path(blog.id), class: 'btn btn-default btn-sm btn-success' %>
      <%= link_to "削除", blog_path(blog.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
    </div>
    <% end %>
    
    
  </div>
</div>

app/views/blogs/new.html.erb
<div class="container">
<div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
<h2>Instagramを作成する</h2>
<%= render 'form' %>
</div>
</div>