config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
get 'contacts/create'
  
resources :poems, only: [:index, :show] 

resources :blogs, only: [:index, :new, :create, :edit, :update ,:destroy] do
    collection do
      post :confirm
    end
  end

resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end
  
  root 'top#index'

  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
validates :name, presence: true
validates :email, presence: true
validates :content, presence: true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
      if params[:back]
      @contact = Contact.new(contacts_params)
    else
      @contact = Contact.new
    end
  end
  def create
    @contact = Contact.new(contacts_params)
    if @contact.save
    redirect_to root_path, notice: "お問い合わせありがとうございました！"
    NoticeMailer.sendmail_contact(@contact).deliver
    else
    render 'new'
    end
  end
def confirm
    @contact = Contact.new(contacts_params)
    render :new if @contact.invalid?
end
  private
    def contacts_params
      params.require(:contact).permit(:name, :email, :content)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
<h3>以下の内容で、送信する。</h3>

<%= form_for(@contact) do |f| %>
  <!-- `f.hidden_field`を使用して、リクエストパラメータに値を設定できるようにしています。 -->
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
  <%= f.hidden_field :content %>

  <!-- @contact.*****とすることで、表示用の値を画面に出力しています。 -->
  <p>名前:<%= @contact.name %></p>
  <p>メールアドレス:<%= @contact.email %></p>
  <p>内容:<%= @contact.content %></p>
  <%= f.submit '登録する',class: 'btn btn-primary btn-block' %>
<% end %>

<%= form_for(@contact, url: new_contact_path, method: 'get') do |f| %>
  <%= f.hidden_field :name %>
  <%= f.hidden_field :email %>
  <%= f.hidden_field :content %>
  <%= f.submit "もどる",name:'back', class: 'btn btn-default btn-sm btn-success' %>
<% end %>

</div>
</div>

app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

app/views/contacts/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

<p id="notice"><%= notice %></p>

<h1>お問い合わせ投稿画面</h1>

<%= form_for(@contact, url: confirm_contacts_path) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= @contact.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.label :名前 %>
  <%= f.text_field :name, class: 'form-control' %>                                                                                   
  <br>
  <%= f.label :メールアドレス %>
  <%= f.text_field :email, class: 'form-control' %>
  <br>
  <%= f.label :内容 %>
  <%= f.text_field :content, class: 'form-control' %>
  <br>
  <%= f.submit '送信', class: 'btn btn-primary btn-block' %>
<% end %>

<%= link_to "お問い合わせ投稿画面にもどる", new_contact_path, class: 'btn btn-default btn-sm btn-success' %>

  </div>
</div>