config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
get 'contacts/create'
  
resources :poems, only: [:index, :show] 

resources :blogs, only: [:index, :new, :create, :edit, :update ,:destroy] do
    collection do
      post :confirm
    end
  end

resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end
  
  root 'top#index'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instagram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <header>
<li><%= link_to "TOP", root_path %></li>
<li class="dropdown">
<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
<ul class="dropdown-menu">
  <li><%= link_to "Instagram", blogs_path %></li>
</ul>
</li>
<% if user_signed_in? %>
<li><%= link_to 'マイページ', edit_user_registration_path %></li>
  <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
<% else %>
  <li><%= link_to 'ログイン', new_user_session_path  %></li>
  <li><%= link_to 'サインアップ', new_user_registration_path %></li>
<% end %>

    </ul>
          </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  </header>

<%= yield %>

  <footer>
    <p>JIBUN株式会社</p>
    <p>© 2015-2016 Copyright JIBUN Corp.</p>
  </footer>

</body>
</html>